[workspace]
members = [
    ".",
    "rorm-db",
    "rorm-declaration",
    "rorm-sql",
]

[package]
name = "rorm-lib"
version = "0.3.0"
edition = "2021"
keywords = ["database", "library"]
authors = ["myOmikron <git@omikron.dev>"]
categories = ["database", "development-tools.categories.ffi"]
repository = "https://github.com/rorm-orm/rorm-lib"
homepage = "https://rorm.rs"
documentation = "https://docs.rorm.rs"
license = "MIT"
description = "The FFI bindings to C."

[lib]
name = "rorm"
crate-type = ["staticlib", "cdylib"]

[dependencies]
rorm-db = { version = "~0.4", path = "rorm-db" }

# Runtime to execute the async context in
tokio = { version = "~1.23" }

# Async wrapper
futures = { version = "~0.3" }

# SQLX is only needed for error unwrapping
sqlx = { version = "~0.6" }

# Date and time library
chrono = { version = "~0.4" }

# Optional logging framework
env_logger = { version = "~0.10", optional = true }

[features]
default = [
    "rorm-db/tokio-rustls",
    "tokio/rt-multi-thread",
]

logging = ["dep:env_logger"]
